# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 18:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dw_blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dw_blog.Cat'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='dw_blog.Tag'),
        ),
        migrations.AddField(
            model_name='imagestore',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dw_blog.Post'),
        ),
    ]
